package com.example.museoartiglieriaapp.Repository

import com.example.museoartiglieriaapp.Models.StorageItem

object StorageRepository {
    
    fun getItemsByCategory(category: String): List<StorageItem> {
        return when (category) {
            "tanks" -> getTanksList()
            "firearms" -> getFirearmsList()
            "artillery" -> getArtilleryList()
            "aircraft" -> getAircraftList()
            "military_equipment" -> getMilitaryEquipmentList()
            "edged_weapons" -> getEdgedWeaponsList()
            else -> emptyList()
        }
    }
    
    private fun getTanksList(): List<StorageItem> = listOf(
        StorageItem("m13_40", "M13/40", "placeholder_image_url", "Italy", "1940", "WWII (North Africa)", "Libya, 1940", "The M13/40 was Italy's most common tank during WWII. It was outmatched by British and American designs, but served throughout the North African campaign. Its performance was limited by poor armor and firepower, but it represented Italy's effort to modernize its armored forces. Some were captured and reused by both Allies and Axis forces.", "placeholder_trivia_data", "placeholder_technical_specs", "tanks"),
        StorageItem("t34_85", "T-34/85", "placeholder_image_url", "Soviet Union", "1944", "WWII, Korean War, Cold War", "Eastern Front, 1944", "An improved version of the revolutionary T-34, the T-34/85 could finally match German Tigers and Panthers. Its mix of firepower, armor, and mobility made it the Red Army's top tank late in the war. The T-34/85 helped secure Soviet victory in Eastern Europe and became a symbol of Soviet military strength. Its design heavily influenced post-war armored doctrines.", "placeholder_trivia_data", "placeholder_technical_specs", "tanks"),
        StorageItem("is2", "IS-2", "placeholder_image_url", "Soviet Union", "1944", "WWII", "Eastern Front, 1944", "Designed to destroy German heavy tanks and fortifications, the IS-2 was the Soviet Union's most powerful tank of the war. Its massive 122 mm gun was deadly against armor and bunkers. The IS-2 led the charge into Berlin in 1945, symbolizing Soviet strength. Post-war, it was gradually replaced but remained in service for decades in allied nations.", "placeholder_trivia_data", "placeholder_technical_specs", "tanks"),
        StorageItem("mark_i", "Mark I", "placeholder_image_url", "United Kingdom", "1916", "World War I", "Battle of the Somme, September 15", "The Mark I was the first tank ever used in battle. Developed by the United Kingdom to overcome the trenches and barbed wire of trench warfare, it broke the stalemate on the Western Front. Despite mechanical and logistical challenges, it forever changed land warfare, paving the way for armored warfare in the 20th century.", "placeholder_trivia_data", "placeholder_technical_specs", "tanks"),
        StorageItem("panzer_iv", "Panzer IV", "placeholder_image_url", "Germany", "1937", "World War II", "Invasion of Poland, 1939", "The Panzer IV was the backbone of the German armored forces during WWII. Initially a support tank, it was continually upgraded to face newer Allied designs. It fought on all major fronts, from France to the Eastern Front. Its adaptability and ease of production made it the most produced German tank of the war. Later models featured stronger guns and armor to counter Soviet T-34s.", "placeholder_trivia_data", "placeholder_technical_specs", "tanks"),
        StorageItem("tiger_i", "Tiger I", "placeholder_image_url", "Nazi Germany", "1942", "WWII", "Leningrad, 1942", "The Tiger I was designed to dominate Allied armor with its powerful 88 mm gun and thick armor. It was nearly invulnerable from the front, but complex and prone to mechanical failure. It became a legendary tank, feared for its killing power, especially in open battle. However, its limited numbers and high cost hindered Germany's ability to mass-deploy it.", "placeholder_trivia_data", "placeholder_technical_specs", "tanks")
    )
    
    private fun getFirearmsList(): List<StorageItem> = listOf(
        StorageItem("mp40", "MP40", "placeholder_image_url", "Nazi Germany", "1938", "WWII", "Early WWII (Poland, 1939)", "The MP40 was the most recognizable German SMG of WWII, known for its folding stock and use by paratroopers and infantry alike. It was designed for ease of use and mass production, becoming an icon of German infantry firepower. Its influence persists in modern SMG designs worldwide.", "placeholder_trivia_data", "placeholder_technical_specs", "firearms"),
        StorageItem("m91_30", "M91/30", "placeholder_image_url", "Soviet Union / Russia", "1930", "WWI (early models), WWII, Cold War", "Russian Imperial Army, 1891 (original design)", "One of the most widely produced military rifles in history, the Mosin-Nagant M91/30 was famed for its durability and accuracy under harsh conditions. It played a decisive role on the Eastern Front of WWII and was widely distributed to Soviet allies. Its design remained largely unchanged for decades, attesting to its effectiveness.", "placeholder_trivia_data", "placeholder_technical_specs", "firearms"),
        StorageItem("sten_gun", "STEN GUN", "placeholder_image_url", "United Kingdom", "1941", "WWII, post-war conflicts", "Early WWII", "Designed for mass production under wartime constraints, the Sten was cheap, easy to manufacture, and widely issued to British and Commonwealth forces. Despite some reliability issues, it was praised for its simplicity and effectiveness in guerrilla warfare and urban combat. Its design influenced many postwar submachine guns.", "placeholder_trivia_data", "placeholder_technical_specs", "firearms"),
        StorageItem("m1934", "M1934", "placeholder_image_url", "Italy", "1934", "WWII, Post-war", "Second Italo-Ethiopian War, 1935", "The Beretta M1934 was widely issued to Italian forces during World War II. Known for its compact size and reliability, it was also used by police and paramilitary units in Italy and abroad. Its simple design made it easy to maintain even in harsh battlefield conditions. Post-war, it continued to serve many countries as a standard sidearm.", "placeholder_trivia_data", "placeholder_technical_specs", "firearms"),
        StorageItem("m91", "M91", "placeholder_image_url", "Italy", "1891", "WWI, WWII", "Italian Army service, 1891", "The Carcano M91 rifle served as the backbone of Italian infantry for over 50 years. Its design influenced many variants and was Italy's primary infantry rifle through two world wars. Despite criticism over its stopping power, it was valued for its accuracy and ruggedness. The rifle also saw limited use in other countries post-WWII.", "placeholder_trivia_data", "placeholder_technical_specs", "firearms"),
        StorageItem("m1a1", "M1A1", "placeholder_image_url", "United States", "1928", "WWII, Prohibition Era", "Used by law enforcement and military from late 1920s", "Famous for use in WWII and by gangsters during the Prohibition, the Tommy Gun combined high fire rate with portability and ruggedness. It was highly regarded by soldiers for close-quarter combat. The weapon's distinctive profile made it a symbol of American military and popular culture.", "placeholder_trivia_data", "placeholder_technical_specs", "firearms")
    )
    
    private fun getArtilleryList(): List<StorageItem> = listOf(
        StorageItem("artillery_1", "Sample Artillery 1", "placeholder_image_url", "Sample Origin", "1940", "WWII", "Sample First Appearance", "Sample brief history for artillery piece 1.", "placeholder_trivia_data", "placeholder_technical_specs", "artillery"),
        StorageItem("artillery_2", "Sample Artillery 2", "placeholder_image_url", "Sample Origin", "1941", "WWII", "Sample First Appearance", "Sample brief history for artillery piece 2.", "placeholder_trivia_data", "placeholder_technical_specs", "artillery"),
        StorageItem("artillery_3", "Sample Artillery 3", "placeholder_image_url", "Sample Origin", "1942", "WWII", "Sample First Appearance", "Sample brief history for artillery piece 3.", "placeholder_trivia_data", "placeholder_technical_specs", "artillery")
    )
    
    private fun getAircraftList(): List<StorageItem> = listOf(
        StorageItem("aircraft_1", "Sample Aircraft 1", "placeholder_image_url", "Sample Origin", "1940", "WWII", "Sample First Appearance", "Sample brief history for aircraft 1.", "placeholder_trivia_data", "placeholder_technical_specs", "aircraft"),
        StorageItem("aircraft_2", "Sample Aircraft 2", "placeholder_image_url", "Sample Origin", "1941", "WWII", "Sample First Appearance", "Sample brief history for aircraft 2.", "placeholder_trivia_data", "placeholder_technical_specs", "aircraft"),
        StorageItem("aircraft_3", "Sample Aircraft 3", "placeholder_image_url", "Sample Origin", "1942", "WWII", "Sample First Appearance", "Sample brief history for aircraft 3.", "placeholder_trivia_data", "placeholder_technical_specs", "aircraft")
    )
    
    private fun getMilitaryEquipmentList(): List<StorageItem> = listOf(
        StorageItem("ushanka", "Ushanka", "placeholder_ushanka.jpg", "Soviet Union", "1930s", "WWII, Cold War", "Russo-Finnish War, 1939", "The Ushanka was introduced to protect Soviet troops from the brutal winter. With fold-down ear flaps and thick insulation, it became essential on the Eastern Front. Beyond function, it became a cultural symbol of the Red Army and Soviet identity, still used in military and ceremonial uniforms today.", "placeholder_trivia_content", "placeholder_technical_specs", "military_equipment"),
        StorageItem("ss_coat", "SS Coat", "placeholder_ss_coat.jpg", "Nazi Germany", "1933-1945", "WWII", "Germany, 1933", "The SS uniform was designed for intimidation and identity. Early versions used black wool with skull insignia, while later combat versions adopted subdued tones. It was both functional and symbolic of Nazi ideology. Highly regulated in appearance, the SS coat was central to the image of elite German units, though practicality in the field forced revisions and simplification during the war.", "placeholder_trivia_content", "placeholder_technical_specs", "military_equipment"),
        StorageItem("brodie_helmet", "Brodie", "placeholder_brodie.jpg", "United Kingdom", "1915", "WWI, WWII", "Battle of Loos, 1915", "The Brodie helmet, or 'shrapnel helmet,' was Britain's response to trench warfare's deadly overhead bursts. Its design protected mainly from falling debris. Used throughout both World Wars with minor updates, it became a symbol of the British soldier—'the Tommy'—especially on the Western Front and during the Blitz.", "placeholder_trivia_content", "placeholder_technical_specs", "military_equipment"),
        StorageItem("adrian_helmet", "Helmet", "placeholder_adrian_helmet.jpg", "France", "1915", "WWI, WWII", "Western Front, 1915", "Originally designed by the French in 1915, the Adrian helmet was adopted by the Italian Army during WWI. It was one of the first standardized steel helmets used to protect soldiers from shrapnel and head injuries. Its design was influential and used by many Allied countries.", "placeholder_trivia_content", "placeholder_technical_specs", "military_equipment"),
        StorageItem("m33_uniform", "M33", "placeholder_m33.jpg", "Italy", "1933-1945", "WWII", "Ethiopia, 1935", "The M33 uniform, worn during Italy's colonial wars and WWII, reflected Italian military aesthetics and industrial constraints. Though practical in temperate climates, it fared poorly in desert and alpine conditions.", "placeholder_trivia_content", "placeholder_technical_specs", "military_equipment"),
        StorageItem("m1_helmet", "M1", "placeholder_m1.jpg", "United States", "1941", "WWII, Korea, Vietnam", "Pearl Harbor, 1941", "The M1 helmet replaced the M1917 and became the most recognizable U.S. headgear of the 20th century. Its ergonomic design and two-part construction offered durability, comfort, and adaptability across decades. Used by millions of American troops, it was a symbol of the GI and served in almost every theater of war. Variants of the M1 continued service in allied armies long after WWII.", "placeholder_trivia_content", "placeholder_technical_specs", "military_equipment")
    )
    
    private fun getEdgedWeaponsList(): List<StorageItem> = listOf(
        StorageItem("nkm_bayonet", "Nkm", "placeholder_nkm.jpg", "Soviet Union", "1940", "WWII", "Eastern Front, 1941", "The NKM-type spike bayonet, issued with the Mosin-Nagant rifles, was a simple but deadly thrusting weapon. Permanently affixed in many cases, it was never meant for slashing. Its simplicity made it cheap to produce, and it doubled as a multi-use tool. Some Soviet troops used it as a pry bar or tent peg in the field.", "placeholder_trivia_content", "placeholder_technical_specs", "edged_weapons"),
        StorageItem("m1891_bayonet", "M1891", "placeholder_m1891.jpg", "Nazi Germany", "1933-1945", "WWII", "Germany, 1933", "Designed for the Carcano Mod. 91 rifle, this bayonet was a versatile tool for Italian infantry. It came in various forms—fixed or folding—and was adapted over decades. It saw use in colonial wars, WWI, and WWII, remaining in service into the postwar era. Its design influenced later military knives and parade models.", "placeholder_trivia_content", "placeholder_technical_specs", "edged_weapons"),
        StorageItem("m3_fighting_knife", "M3", "placeholder_m3.jpg", "United States", "1943", "WWII", "Italy, 1943", "The M3 Fighting Knife was developed for U.S. paratroopers and commandos during WWII. Slim, lightweight, and effective in close combat, it was preferred in trench raids and night ops. The M3's success led to its transformation into the M4 bayonet and influenced later combat knives like the M7 and M9.", "placeholder_trivia_content", "placeholder_technical_specs", "edged_weapons"),
        StorageItem("lebel_bayonet", "Lebel", "placeholder_lebel.jpg", "France", "1886", "WWI, WWII", "1886 with Lebel Rifle", "The Épée-Baïonnette Modèle 1886, known simply as 'Lebel,' was a French bayonet designed for thrusting, not slashing. Its cruciform blade made wounds hard to treat, drawing criticism. It was issued en masse in WWI, remaining in use into WWII. Often modified or shortened in the interwar years, it remains one of history's longest standard bayonets.", "placeholder_trivia_content", "placeholder_technical_specs", "edged_weapons"),
        StorageItem("seitengewehr", "Seitengewehr", "placeholder_seitengewehr.jpg", "Germany", "1898", "WWI, WWII", "Mauser 98 rifle, 1898", "'Seitengewehr' (literally 'sidearm') bayonets were issued to German troops alongside Mauser rifles. Models evolved, but all featured robust blades for close combat and rifle mounting. Used in both world wars, they symbolized German military efficiency and were often customized by troops. Some had sawback versions for engineers.", "placeholder_trivia_content", "placeholder_technical_specs", "edged_weapons"),
        StorageItem("pattern_1907_bayonet", "1907", "placeholder_1907.jpg", "United Kingdom", "1907", "WWI, WWII", "With SMLE rifle, 1908", "The Pattern 1907 bayonet was designed for use with the Short Magazine Lee-Enfield rifle. Its long blade was suited for trench fighting and mass infantry tactics. It remained the standard British bayonet through both world wars, sometimes reissued with updated grips or shorter blades.", "placeholder_trivia_content", "placeholder_technical_specs", "edged_weapons")
    )
} 